version: "3"

services:
  app:
    build: nginx/
    ports:
      - "8081:8000"
      - "8443:8443"
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:delegated
      - ./src:/var/www/html/
      - sockdata:/sock
      - ./default.conf:/etc/nginx/conf.d/default.conf:delegated
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:delegated


  phpfpm:
    build: php/
    links:
      - db
    volumes: *appvolumes

  db:
    image: mariadb
    ports:
      - "3306:3306"
    env_file: ./db.env
    volumes:
      - ./dbdata/:/var/lib/mysql

  redis:
    image: redis:5.0

  elasticsearch:
    image: elasticsearch:5.6
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  appdata:
  sockdata: